# Part 1 — Generating Real Embeddings in Python
# embeddings are generated by a trained neural network, sentence-transformers, a library built on top of Hugging Face transformer models, specifically designed to turn sentences into dense embedding vectors.
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

sentences = [
    "The cat sat on the mat",
    "Dogs are loyal animals",
    "The stock market crashed today"
]

embeddings = model.encode(sentences)
# print(embeddings)  # (3, 384)

# Transformer → creates meaningful numerical representations.
# Embedding → is that numerical representation.
# Cosine similarity → compares representations.
# FAISS → efficiently searches many representations.

# Part 2 — Introduction to FAISS
# FAISS (Facebook AI Similarity Search) is a library for fast similarity search over large collections of vectors. It doesn't generate embeddings (that's sentence-transformers's job) — it takes embeddings you already have and lets you search through millions of them in milliseconds.
# Index — a data structure FAISS builds over your vectors to make search fast. Different index types trade off speed vs. accuracy vs. memory.
# IndexFlatL2 — the simplest index. "Flat" means no clever tricks — it's literally brute-force Euclidean (L2) distance search under the hood, but implemented in highly optimized C++. Good baseline, 100% accurate, but doesn't scale to huge datasets as well as approximate indexes.
# IndexFlatIP — same idea but uses inner product (dot product) instead of L2 distance. If your vectors are normalized (magnitude = 1, remember Session 1!), inner product search gives you the same ranking as cosine similarity search
# Approximate indexes (e.g., IndexIVFFlat, IndexHNSWFlat) — for millions/billions of vectors, exact search is too slow, so FAISS offers indexes that sacrifice a tiny bit of accuracy for massive speed gains.

from sentence_transformers import util

query_embedding = model.encode("Tell me about pets")
doc_embeddings = model.encode(sentences)

# built-in cosine similarity utility (same math you wrote by hand)
scores = util.cos_sim(query_embedding, doc_embeddings)
# print(scores)

import faiss
import numpy as np

dimension = 384  # matches our embedding size from all-MiniLM-L6-v2

index = faiss.IndexFlatL2(dimension)  # build an empty index

# doc_embeddings from earlier — FAISS needs float32 numpy arrays
doc_embeddings = np.array(doc_embeddings).astype('float32')
index.add(doc_embeddings)  # add our document vectors to the index

# print(index.ntotal)  # number of vectors in the index

# search: find the k nearest vectors to a query
query_embedding = np.array([query_embedding]).astype('float32')  # must be 2D
k = 2  # how many results you want
distances, indices = index.search(query_embedding, k)

print(distances)  # L2 distances to the closest matches
print(indices)    # index positions of the closest matches in doc_embeddings